---
title: "DDS Assignment 9"
author: "Benjamin Wilke"
date: "March 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Required Libraries

```{r}
library("xml2")
library("rvest")
library("kableExtra")
library("tidyr")
library("ggplot2")
```

## Harry Potter Cast

Scrape initial data, perform appropriate cleaning, and put into a single data frame for presentation.

```{r}

url <- "http://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1"  # URL of site to scrape

cast <- url %>%   #scrape the table from the site
  read_html() %>%
  html_nodes(xpath='//*[@id="fullcredits_content"]/table[3]') %>%
  html_table()

cast <- cast[[1]] # move from list of 1 to own data frame
actornames <- cast$X2 # extract actor names
characternames <- cast$X4 # extract character names

characternames <- gsub(" \n  \n  \n  ", " ", characternames) # replaces a funky string with a space

characternames <- characternames[-c(1, 93)] # remove 1st and 93rd row
actornames <- actornames[-c(1, 93)]  # remove 1st and 93rd row

actornames <- do.call(rbind, strsplit(actornames, ' (?=[^ ]+$)', perl=TRUE)) # split actornames on last space

firstname <- actornames[1:149] # store first name
lastname <- actornames[1:149,2] # store last name

harrypottercast <- data.frame(firstname, lastname, characternames) # create final data frame

which(grepl("Warwick", harrypottercast$firstname))  # show mr. warwick
harrypottercast[10,]  # shows Warwick's character before fixing

harrypottercast <- data.frame(lapply(harrypottercast, as.character), stringsAsFactors=FALSE) #convert to strings from factors

harrypottercast$characternames[harrypottercast$characternames == "Griphook /  \n            Professor Filius Flitwick"] <- "Griphook / Professor Filius Flitwick"  # fix mr. warwick 

harrypottercast[10,]  # shows Warwick's character after fixing

colnames(harrypottercast) <- c("ActorFirstName", "ActorLastName", "CharacterName") # apply better column names

harrypottercast_head <- head(harrypottercast, 10) #show first 10 rows
knitr::kable(harrypottercast_head,caption = "First 10 Rows", row.names = FALSE, "html") %>%
  kable_styling(bootstrap_options = c("striped","hover","condensed"))

harrypottercast_tail <- tail(harrypottercast, 10) #show last 10 rows
knitr::kable(harrypottercast_tail,caption = "Last 10 Rows", row.names = FALSE, "html") %>%
  kable_styling(bootstrap_options = c("striped","hover","condensed"))

```

## SportsBall

``` {r}

url2 <- "http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs"

shootingstats <- url2 %>%   #scrape the table from the site
  read_html() %>%
  html_nodes(xpath='//*[@id="my-players-table"]/div[3]/div[3]/table') %>%
  html_table()

shootingstats <- shootingstats[[1]] # reduce depth of list

namestemp <- shootingstats$X1
namestemp <- strsplit(namestemp, ', ') # split player name and position

namestemp <- as.data.frame(namestemp) # convert to data frame from list for ease
namestemp <- t(namestemp)

player <- namestemp[1:20] # temp var for player
position <- namestemp[1:20,2] # temp var for position

shootingstats <- data.frame(player, position, shootingstats$X2, shootingstats$X3, shootingstats$X4, shootingstats$X5, shootingstats$X6, shootingstats$X7, shootingstats$X8, shootingstats$X9, shootingstats$X10, shootingstats$X11, shootingstats$X12, shootingstats$X13, shootingstats$X14, shootingstats$X15)

row.names(shootingstats) <- NULL # get rid of funky rownames

colnames(shootingstats) <- c("Player","Position","FGM","FGA","FGPercent","ThreePM","ThreePA","ThreePPercent","FTM","FTA","FTPercent","TwoPM","TwoPA","TwoPPercent","PPS","AFGPercent") # rename columne to something nices

shootingstats <- shootingstats[-c(1,2,20),] # get rid of junk first rows and total

sapply(shootingstats, class) # show class of each column

# convert columns to appropriate class

shootingstats$Player <- as.character(shootingstats$Player)
shootingstats$Position <- as.character(shootingstats$Position)

# because these numbers were stored as factors we need to convert to character first

shootingstats$FGM <- as.character(shootingstats$FGM)
shootingstats$FGA <- as.character(shootingstats$FGA)
shootingstats$FGPercent <- as.character(shootingstats$FGPercent)
shootingstats$ThreePM <- as.character(shootingstats$ThreePM)
shootingstats$ThreePA <- as.character(shootingstats$ThreePA)
shootingstats$ThreePPercent <- as.character(shootingstats$ThreePPercent)
shootingstats$FTM <- as.character(shootingstats$FTM)
shootingstats$FTA <- as.character(shootingstats$FTA)
shootingstats$FTPercent <- as.character(shootingstats$FTPercent)
shootingstats$TwoPM <- as.character(shootingstats$TwoPM)
shootingstats$TwoPA <- as.character(shootingstats$TwoPA)
shootingstats$TwoPPercent <- as.character(shootingstats$TwoPPercent)
shootingstats$PPS <- as.character(shootingstats$PPS)
shootingstats$AFGPercent <- as.character(shootingstats$AFGPercent)

# now we can convert to numeric

shootingstats$FGM <- as.numeric(shootingstats$FGM)
shootingstats$FGA <- as.numeric(shootingstats$FGA)
shootingstats$FGPercent <- as.numeric(shootingstats$FGPercent)
shootingstats$ThreePM <- as.numeric(shootingstats$ThreePM)
shootingstats$ThreePA <- as.numeric(shootingstats$ThreePA)
shootingstats$ThreePPercent <- as.numeric(shootingstats$ThreePPercent)
shootingstats$FTM <- as.numeric(shootingstats$FTM)
shootingstats$FTA <- as.numeric(shootingstats$FTA)
shootingstats$FTPercent <- as.numeric(shootingstats$FTPercent)
shootingstats$TwoPM <- as.numeric(shootingstats$TwoPM)
shootingstats$TwoPA <- as.numeric(shootingstats$TwoPA)
shootingstats$TwoPPercent <- as.numeric(shootingstats$TwoPPercent)
shootingstats$PPS <- as.numeric(shootingstats$PPS)
shootingstats$AFGPercent <- as.numeric(shootingstats$AFGPercent)

sapply(shootingstats, class) # show class of each column again to verify that they were changed correctly

shootingstats_table <- head(shootingstats, 17) #show player stats table
knitr::kable(shootingstats_table,caption = "Shooting Statistics", row.names = FALSE, "html") %>%
  kable_styling(bootstrap_options = c("striped","hover","condensed"))

plotdata <- data.frame(shootingstats$Player, shootingstats$FGPercent, shootingstats$Position)


ggplot(data=shootingstats, aes(x=reorder(Player, FGPercent), y=FGPercent, fill=Position)) +
  geom_bar(stat='identity', color='black') +
  xlab("Player") + ylab("Field Goal Percentage") +
  ggtitle("Field Goal Percentages per Game") + 
  coord_flip()
```


